# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/VLSI/Desktop/Vivado_Code/Accelerator_Templete/Accelerator_Templete.srcs/sources_1/ip/gbf_16x1024/gbf_16x1024.xci
# IP: The module: 'gbf_16x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/VLSI/Desktop/Vivado_Code/Accelerator_Templete/Accelerator_Templete.gen/sources_1/ip/gbf_16x1024/gbf_16x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gbf_16x1024'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/VLSI/Desktop/Vivado_Code/Accelerator_Templete/Accelerator_Templete.srcs/sources_1/ip/gbf_16x1024/gbf_16x1024.xci
# IP: The module: 'gbf_16x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/VLSI/Desktop/Vivado_Code/Accelerator_Templete/Accelerator_Templete.gen/sources_1/ip/gbf_16x1024/gbf_16x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gbf_16x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
