# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/VLSI/Desktop/Vivado_Code/Accelerator_Templete/Accelerator_Templete.srcs/sources_1/ip/psum_gbf_512x32/psum_gbf_512x32.xci
# IP: The module: 'psum_gbf_512x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/VLSI/Desktop/Vivado_Code/Accelerator_Templete/Accelerator_Templete.gen/sources_1/ip/psum_gbf_512x32/psum_gbf_512x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'psum_gbf_512x32'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/VLSI/Desktop/Vivado_Code/Accelerator_Templete/Accelerator_Templete.srcs/sources_1/ip/psum_gbf_512x32/psum_gbf_512x32.xci
# IP: The module: 'psum_gbf_512x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/VLSI/Desktop/Vivado_Code/Accelerator_Templete/Accelerator_Templete.gen/sources_1/ip/psum_gbf_512x32/psum_gbf_512x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'psum_gbf_512x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
